In [2]:
# 1. Import the numpy package under the name 'np.

import numpy as np

In [2]:
# 2. Print the numpy version and the configuration

# Check version:-
print(np.__version__)

# Check configuration
print(np.show_config())



1.22.1
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

In [3]:
# 3. Create a null vector of size 10

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4. How to find the memory size of any array

# - By using SIZE and ITEMSIZE attributes in NumPy array.

arr1 = np.array([[1,2,3,4],[5,6,7,8]])

print("Size of the array: ", arr1.size)

print("Memory Size of one array element in bytes: ", arr1.itemsize)

print("Memory size of numpy array in bytes: ", arr1.size * arr1.itemsize)

# By using NBYTES attributes in NumPy array.

print("Memory size of a Numpy array by using nbytes: ", arr1.nbytes)

Size of the array:  8
Memory Size of one array element in bytes:  4
Memory size of numpy array in bytes:  32
Memory size of a Numpy array by using nbytes:  32


In [5]:
# 5. How to get the documentation of the numpy add function from the command line?

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#  6. Create a null vector of size 10 but the fifth value which is 1?

arr3 = np.zeros(10)
arr3[4] = 1
arr3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7. Create a vector with values ranging from 10 to 49?

arr4 = np.arange(10,50)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8. Reverse a vector (first element becomes last)?
arr5 = np.arange(0, 6)
print("Original array: ", arr5)

print("Reverse array: ", arr5[::-1])

Original array:  [0 1 2 3 4 5]
Reverse array:  [5 4 3 2 1 0]


In [9]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8?

arr6 = np.arange(0, 9).reshape(3,3)
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]?

arr7 = np.array([1,2,0,0,4,0])
print("Original array: ", arr7)
non_zero = np.nonzero(arr7)
print("Indices of non-zero elements: ", non_zero)

Original array:  [1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [11]:
# 11. Create a 3x3 identity matrix

arr8 = np.identity(3)
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [1]:
import numpy as np

In [4]:
# 12. Create a 3x3x3 array with random values?

a = np.random.random((3,3,3))
a

array([[[0.12257375, 0.83511525, 0.8704178 ],
        [0.67925854, 0.88723511, 0.62332253],
        [0.44789724, 0.23614966, 0.69039328]],

       [[0.44174477, 0.40549936, 0.52295011],
        [0.76064488, 0.77591492, 0.23836426],
        [0.26641595, 0.71406878, 0.70058828]],

       [[0.85521982, 0.54535653, 0.93799363],
        [0.99669982, 0.01836937, 0.39520238],
        [0.56112147, 0.78996926, 0.84025012]]])

In [6]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values?

b = np.random.random((10,10))
print("Original array: ", b)
print("The minimum value of b:  ", b.min())
print("The maximum value of b: ", b.max())

Original array:  [[0.88984428 0.53424115 0.82057146 0.58657403 0.27901961 0.63190431
  0.2331149  0.21491014 0.35184622 0.43365967]
 [0.14554665 0.08530893 0.18278467 0.12727511 0.58832575 0.6403771
  0.37635159 0.59518967 0.41956287 0.38296331]
 [0.55939892 0.06798275 0.51344948 0.40100442 0.5751992  0.08840878
  0.16297043 0.94498744 0.38579268 0.32034089]
 [0.250223   0.29319566 0.13595331 0.42820078 0.57538895 0.75292218
  0.13234062 0.07722104 0.80381801 0.77631641]
 [0.71694441 0.55078494 0.30684618 0.25055969 0.74164485 0.30630771
  0.74010755 0.84997933 0.59857399 0.61069802]
 [0.93926304 0.04431812 0.46113642 0.33187628 0.38773759 0.17680455
  0.81744295 0.344628   0.29258765 0.69894783]
 [0.70274608 0.77524507 0.30250485 0.31907101 0.19180169 0.84803334
  0.09492183 0.23523386 0.21026042 0.56574729]
 [0.92383793 0.13073511 0.78759934 0.17441381 0.26791889 0.03146355
  0.50827603 0.6038614  0.31848409 0.7762379 ]
 [0.48759672 0.69087596 0.81688849 0.62273641 0.69288402 0.08997

In [7]:
# 14. Create a random vector of size 30 and find the mean value ?

c = np.random.random(30)
print("Original array: ", c)
print("Mean of above array: ", c.mean())

Original array:  [0.83149841 0.83824648 0.84570987 0.11788885 0.09647802 0.73093662
 0.91046703 0.28197239 0.04762872 0.44462023 0.65375404 0.67671492
 0.56644289 0.74895418 0.97178646 0.66500377 0.94518908 0.16883021
 0.02823011 0.05339857 0.21583533 0.29402418 0.73808309 0.76708131
 0.98053343 0.38046534 0.93914997 0.68126977 0.82894115 0.26032772]
Mean of above array:  0.5569820714003111


In [10]:
# 15. Create a 2d array with 1 on the border and 0 inside?

d = np.ones((4,4))

print("Original array: ", d)

d[1:-1, 1:-1]=0

print("Output array: ",d)

Original array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Output array:  [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [11]:
'''17. What is the result of the following expression? (★☆☆)
python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1'''

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [12]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal?

e = np.diag(1+np.arange(4),k=-1)
print(e)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [13]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

f = np.zeros((8,8), dtype = int)
f[1::2,::2] = 1
f[::2, 1::2]=1
print("Checkbox pattern", f)


Checkbox pattern [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
# 20. How to find common values between two arrays? (★☆☆)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 3 4 6]


In [ ]:
#  21. How to get the dates of yesterday, today and tomorrow? (★☆☆)

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)