In [1]:
# 1. Import the numpy package under the name 'np.

import numpy as np

In [2]:
# 2. Print the numpy version and the configuration

# Check version:-
print(np.__version__)

# Check configuration
print(np.show_config())



1.22.1
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

In [3]:
# 3. Create a null vector of size 10

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 4. How to find the memory size of any array

# - By using SIZE and ITEMSIZE attributes in NumPy array.

arr1 = np.array([[1,2,3,4],[5,6,7,8]])

print("Size of the array: ", arr1.size)

print("Memory Size of one array element in bytes: ", arr1.itemsize)

print("Memory size of numpy array in bytes: ", arr1.size * arr1.itemsize)

# By using NBYTES attributes in NumPy array.

print("Memory size of a Numpy array by using nbytes: ", arr1.nbytes)

Size of the array:  8
Memory Size of one array element in bytes:  4
Memory size of numpy array in bytes:  32
Memory size of a Numpy array by using nbytes:  32


In [5]:
# 5. How to get the documentation of the numpy add function from the command line?

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#  6. Create a null vector of size 10 but the fifth value which is 1?

arr3 = np.zeros(10)
arr3[4] = 1
arr3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
# 7. Create a vector with values ranging from 10 to 49?

arr4 = np.arange(10,50)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
# 8. Reverse a vector (first element becomes last)?
arr5 = np.arange(0, 6)
print("Original array: ", arr5)

print("Reverse array: ", arr5[::-1])

Original array:  [0 1 2 3 4 5]
Reverse array:  [5 4 3 2 1 0]


In [9]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8?

arr6 = np.arange(0, 9).reshape(3,3)
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]?

arr7 = np.array([1,2,0,0,4,0])
print("Original array: ", arr7)
non_zero = np.nonzero(arr7)
print("Indices of non-zero elements: ", non_zero)

Original array:  [1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [11]:
# 11. Create a 3x3 identity matrix using numpy?

arr8 = np.identity(3)
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])